// 77 จังหวัดในประเทศไทย แบ่งตามภูมิภาค

const provinces = {
  // ภาคเหนือ (17 จังหวัด)
  north: [
    { name: 'เชียงใหม่', slug: 'chiang-mai' },
    { name: 'เชียงราย', slug: 'chiang-rai' },
    { name: 'แม่ฮ่องสอน', slug: 'mae-hong-son' },
    { name: 'ลำปาง', slug: 'lampang' },
    { name: 'ลำพูน', slug: 'lamphun' },
    { name: 'อุตรดิตถ์', slug: 'uttaradit' },
    { name: 'แพร่', slug: 'phrae' },
    { name: 'น่าน', slug: 'nan' },
    { name: 'พะเยา', slug: 'phayao' },
    { name: 'เพชรบูรณ์', slug: 'phetchabun' },
    { name: 'พิษณุโลก', slug: 'phitsanulok' },
    { name: 'สุโขทัย', slug: 'sukhothai' },
    { name: 'ตาก', slug: 'tak' },
    { name: 'กำแพงเพชร', slug: 'kamphaeng-phet' },
    { name: 'พิจิตร', slug: 'phichit' },
    { name: 'นครสวรรค์', slug: 'nakhon-sawan' },
    { name: 'อุทัยธานี', slug: 'uthai-thani' },
  ],

  // ภาคใต้ (14 จังหวัด)
  south: [
    { name: 'ภูเก็ต', slug: 'phuket' },
    { name: 'กระบี่', slug: 'krabi' },
    { name: 'พังงา', slug: 'phang-nga' },
    { name: 'สุราษฎร์ธานี', slug: 'surat-thani' },
    { name: 'นครศรีธรรมราช', slug: 'nakhon-si-thammarat' },
    { name: 'ชุมพร', slug: 'chumphon' },
    { name: 'ระนอง', slug: 'ranong' },
    { name: 'ตรัง', slug: 'trang' },
    { name: 'พัทลุง', slug: 'phatthalung' },
    { name: 'สตูล', slug: 'satun' },
    { name: 'สงขลา', slug: 'songkhla' },
    { name: 'ปัตตานี', slug: 'pattani' },
    { name: 'ยะลา', slug: 'yala' },
    { name: 'นราธิวาส', slug: 'narathiwat' },
  ],

  // ภาคอีสาน (20 จังหวัด)
  northeast: [
    { name: 'นครราชสีมา', slug: 'nakhon-ratchasima' },
    { name: 'บุรีรัมย์', slug: 'buriram' },
    { name: 'สุรินทร์', slug: 'surin' },
    { name: 'ศรีสะเกษ', slug: 'si-sa-ket' },
    { name: 'อุบลราชธานี', slug: 'ubon-ratchathani' },
    { name: 'ยโสธร', slug: 'yasothon' },
    { name: 'ชัยภูมิ', slug: 'chaiyaphum' },
    { name: 'อำนาจเจริญ', slug: 'amnat-charoen' },
    { name: 'หนองบัวลำภู', slug: 'nong-bua-lam-phu' },
    { name: 'ขอนแก่น', slug: 'khon-kaen' },
    { name: 'อุดรธานี', slug: 'udon-thani' },
    { name: 'เลย', slug: 'loei' },
    { name: 'หนองคาย', slug: 'nong-khai' },
    { name: 'มหาสารคาม', slug: 'maha-sarakham' },
    { name: 'ร้อยเอ็ด', slug: 'roi-et' },
    { name: 'กาฬสินธุ์', slug: 'kalasin' },
    { name: 'สกลนคร', slug: 'sakon-nakhon' },
    { name: 'นครพนม', slug: 'nakhon-phanom' },
    { name: 'มุกดาหาร', slug: 'mukdahan' },
    { name: 'บึงกาฬ', slug: 'bueng-kan' },
  ],

  // ภาคกลาง (26 จังหวัด)
  central: [
    { name: 'กรุงเทพมหานคร', slug: 'bangkok' },
    { name: 'นนทบุรี', slug: 'nonthaburi' },
    { name: 'ปทุมธานี', slug: 'pathum-thani' },
    { name: 'สมุทรปราการ', slug: 'samut-prakan' },
    { name: 'สมุทรสาคร', slug: 'samut-sakhon' },
    { name: 'สมุทรสงคราม', slug: 'samut-songkhram' },
    { name: 'นครปฐม', slug: 'nakhon-pathom' },
    { name: 'ชัยนาท', slug: 'chai-nat' },
    { name: 'ลพบุรี', slug: 'lopburi' },
    { name: 'สิงห์บุรี', slug: 'sing-buri' },
    { name: 'อ่างทอง', slug: 'ang-thong' },
    { name: 'พระนครศรีอยุธยา', slug: 'ayutthaya' },
    { name: 'สระบุรี', slug: 'saraburi' },
    { name: 'ชลบุรี', slug: 'chon-buri' },
    { name: 'ระยอง', slug: 'rayong' },
    { name: 'จันทบุรี', slug: 'chanthaburi' },
    { name: 'ตราด', slug: 'trat' },
    { name: 'ฉะเชิงเทรา', slug: 'chachoengsao' },
    { name: 'ปราจีนบุรี', slug: 'prachin-buri' },
    { name: 'นครนายก', slug: 'nakhon-nayok' },
    { name: 'สระแก้ว', slug: 'sa-kaeo' },
    { name: 'กาญจนบุรี', slug: 'kanchanaburi' },
    { name: 'สุพรรณบุรี', slug: 'suphan-buri' },
    { name: 'ราชบุรี', slug: 'ratchaburi' },
    { name: 'เพชรบุรี', slug: 'phetchaburi' },
    { name: 'ประจวบคีรีขันธ์', slug: 'prachuap-khiri-khan' },
  ],
};

module.exports = provinces;
